[project]
name = "launchsampler"
version = "0.1.0"
description = "Simple Launchpad Sampler"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
    "pydantic>=2.12.4",
    "sounddevice>=0.5.3",
]

[project.scripts]
launchsampler = "launchsampler.__main__:main"

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"